version: '3.8'

services:
  influxdb:
    image: influxdb:latest
    ports:
      - '${INFLUXDB__PORT}:8086'
    volumes:
      - influxdb-storage:/var/lib/influxdb
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB__ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB__BUCKET}
      - DOCKER_INFLUXDB_INIT_USERNAME
      - DOCKER_INFLUXDB_INIT_PASSWORD
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN
    restart: unless-stopped

volumes:
    influxdb-storage: